# Site settings
title: myblog
name: Omkar Dhekne # your name
email: ogdhekne@gmail.com # your email address
description: >
    I am hardcore GNU/Linux fan, I do sometimes use BSD distros.
    I like building 3D printer and 3D printing stuff.
    I like shell scriping.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: ogdhekne # your Twitter username
github_username: ogdhekne # your Github username
# disqus_username: ogdhekne # your disqus username

#google-analytics: UA-75034651-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
